### ISSUE TITLE
Transfering ownership

### ISSUE THREAD

**Issue by goodmami** [goodmami/APIdown#6]
This repository is no longer maintained. It will soon be archived. If someone wishes to take over maintainership, it would be best if the following happened:

* [duplicate the repository](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository) (not a fork)
* Add a new owner to the LICENSE file, e.g.:
  ```
  Copyright (c) 2016 Michael Wayne Goodman
  Copyright (c) 2019 Your Name Here
  ```
* Changing the `author`, `author_email`, and `url` fields of `setup.py`
* A notice of the history is added to the `README.md` file; e.g.:
  ### Project History
  This project was created by Michael Wayne Goodman (@goodmami) and is now owned and maintained by ...

Once this is done (or at least the first step) I will update the README of this repository to point to the new home and then archive the repository.

**Comment by jeffhung** [comment]
@goodmami I've duplicated the repository in [jeffhung/RenderDown](https://github.com/jeffhung/RenderDown) and applied the changes through https://github.com/jeffhung/RenderDown/pull/1.

**Comment by goodmami** [comment]
@jeffhung Thanks for that! I've now updated the README and will archive the repo.

Best wishes for your project! I'll have to get you a beer or something the next time I'm in Taipei.
